### ISSUE TITLE
Perl scalar annotations

### ISSUE THREAD

**Issue by makafre** [lukechampine/merkle#2]
Hello,
I noticed that the Perl code gives an error when ran so I am putting the corrected version here:

        while ((scalar @hashes) > 1) {
                my @joinedHashes;
                while (my @pair = splice @hashes, 0, 2) {
                        push @joinedHashes, $pair[1] ? (sha256_hex @pair) : $pair[0];
                }
                @hashes = @joinedHashes;
        }
        $dailyhash = $hashes[0];

The issue is that it was using  @pair[1]  instead of  $pair[1]  , etc.
Otherwise , it works well, thanks for sharing this algo.
-m

**Comment by lukechampine** [comment]
Interesting. I don't get an error, and both versions produce the same result. I'm using Perl v5.22.1. Can you provide more information about how to reproduce the error?

**Comment by makafre** [comment]
To reproduce it just add the following two lines:

use warnings;
use strict;

..since they were not there Perl loosely accepted the code without complaining  :)
Here are the errors when present:

> perl -c ./test.pl
Scalar value @pair[1] better written as $pair[1] at ./test.pl line 20.
Scalar value @pair[0] better written as $pair[0] at ./test.pl line 20.
Scalar value @hashes[0] better written as $hashes[0] at ./test.pl line 24.
Global symbol "$segment" requires explicit package name at ./test.pl line 12.
Global symbol "$segment" requires explicit package name at ./test.pl line 13.
./test.pl had compilation errors.

Cheers

-m

**Comment by lukechampine** [comment]
ah, good old Perl. Thanks!
